runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /bootstrap
  static_dir: bootstrap

- url: /assets
  static_dir: assets
  application_readable: true

- url: /lugares/add
  script: handlers.lugares.add.app

- url: /lugares/show
  script: handlers.lugares.show.app

- url: /lugares/list
  script: handlers.lugares.list.app

- url: /lugares/edit
  script: handlers.lugares.edit.app

- url: /lugares/delete
  script: handlers.lugares.delete.app

- url: /lugares/search
  script: handlers.lugares.search.app

- url: /avisos/add
  script: handlers.avisos.add.app

- url: /avisos/list
  script: handlers.avisos.list.app

- url: /avisos/edit
  script: handlers.avisos.edit.app

- url: /avisos/delete
  script: handlers.avisos.delete.app

- url: /eventos/add
  script: handlers.eventos.add.app

- url: /eventos/main_list
  script: handlers.eventos.main_list.app

- url: /eventos/list
  script: handlers.eventos.list.app

- url: /eventos/edit
  script: handlers.eventos.edit.app

- url: /eventos/show
  script: handlers.eventos.show.app

- url: /eventos/delete
  script: handlers.eventos.delete.app

- url: /lugares/main_search
  script: handlers.lugares.main_search.app

- url: /lugares/search
  script: handlers.lugares.search.app

- url: /eventos/main_search
  script: handlers.eventos.main_search.app

- url: /eventos/search
  script: handlers.eventos.search.app

- url: .*
  script: handlers.main.app

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "latest"
